/*
 * This file is generated by jOOQ.
 */
package dev.luisjohann.jooq.tables;


import dev.luisjohann.jooq.Keys;
import dev.luisjohann.jooq.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Produto extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.produto</code>
     */
    public static final Produto PRODUTO = new Produto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.produto.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.produto.nome</code>.
     */
    public final TableField<Record, String> NOME = createField(DSL.name("nome"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.produto.descricao</code>.
     */
    public final TableField<Record, String> DESCRICAO = createField(DSL.name("descricao"), SQLDataType.VARCHAR(500), this, "");

    private Produto(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Produto(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.produto</code> table reference
     */
    public Produto(String alias) {
        this(DSL.name(alias), PRODUTO);
    }

    /**
     * Create an aliased <code>public.produto</code> table reference
     */
    public Produto(Name alias) {
        this(alias, PRODUTO);
    }

    /**
     * Create a <code>public.produto</code> table reference
     */
    public Produto() {
        this(DSL.name("produto"), null);
    }

    public <O extends Record> Produto(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, PRODUTO);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return (Identity<Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PRODUTO_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.PRODUTO_PKEY);
    }

    @Override
    public Produto as(String alias) {
        return new Produto(DSL.name(alias), this);
    }

    @Override
    public Produto as(Name alias) {
        return new Produto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Produto rename(String name) {
        return new Produto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Produto rename(Name name) {
        return new Produto(name, null);
    }
}
