/*
 * This file is generated by jOOQ.
 */
package dev.luisjohann.jooq;


import dev.luisjohann.jooq.tables.Ajuste;
import dev.luisjohann.jooq.tables.AjusteItem;
import dev.luisjohann.jooq.tables.FlywaySchemaHistory;
import dev.luisjohann.jooq.tables.Operacao;
import dev.luisjohann.jooq.tables.OperacaoItem;
import dev.luisjohann.jooq.tables.Pessoa;
import dev.luisjohann.jooq.tables.Produto;
import dev.luisjohann.jooq.tables.Usuario;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ajuste</code>.
     */
    public final Ajuste AJUSTE = Ajuste.AJUSTE;

    /**
     * The table <code>public.ajuste_item</code>.
     */
    public final AjusteItem AJUSTE_ITEM = AjusteItem.AJUSTE_ITEM;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.operacao</code>.
     */
    public final Operacao OPERACAO = Operacao.OPERACAO;

    /**
     * The table <code>public.operacao_item</code>.
     */
    public final OperacaoItem OPERACAO_ITEM = OperacaoItem.OPERACAO_ITEM;

    /**
     * The table <code>public.pessoa</code>.
     */
    public final Pessoa PESSOA = Pessoa.PESSOA;

    /**
     * The table <code>public.produto</code>.
     */
    public final Produto PRODUTO = Produto.PRODUTO;

    /**
     * The table <code>public.usuario</code>.
     */
    public final Usuario USUARIO = Usuario.USUARIO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Ajuste.AJUSTE,
            AjusteItem.AJUSTE_ITEM,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Operacao.OPERACAO,
            OperacaoItem.OPERACAO_ITEM,
            Pessoa.PESSOA,
            Produto.PRODUTO,
            Usuario.USUARIO);
    }
}
