/*
 * This file is generated by jOOQ.
 */
package dev.luisjohann.jooq;


import dev.luisjohann.jooq.tables.Ajuste;
import dev.luisjohann.jooq.tables.AjusteItem;
import dev.luisjohann.jooq.tables.FlywaySchemaHistory;
import dev.luisjohann.jooq.tables.Operacao;
import dev.luisjohann.jooq.tables.OperacaoItem;
import dev.luisjohann.jooq.tables.Pessoa;
import dev.luisjohann.jooq.tables.Produto;
import dev.luisjohann.jooq.tables.Usuario;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ajuste</code>.
     */
    public static final Ajuste AJUSTE = Ajuste.AJUSTE;

    /**
     * The table <code>public.ajuste_item</code>.
     */
    public static final AjusteItem AJUSTE_ITEM = AjusteItem.AJUSTE_ITEM;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.operacao</code>.
     */
    public static final Operacao OPERACAO = Operacao.OPERACAO;

    /**
     * The table <code>public.operacao_item</code>.
     */
    public static final OperacaoItem OPERACAO_ITEM = OperacaoItem.OPERACAO_ITEM;

    /**
     * The table <code>public.pessoa</code>.
     */
    public static final Pessoa PESSOA = Pessoa.PESSOA;

    /**
     * The table <code>public.produto</code>.
     */
    public static final Produto PRODUTO = Produto.PRODUTO;

    /**
     * The table <code>public.usuario</code>.
     */
    public static final Usuario USUARIO = Usuario.USUARIO;
}
